# Generated by Django 5.1.6 on 2025-12-12 20:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_file_created_at_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_at'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید در فرمت صحیح وارد شود. مثال: +989123456789', regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تلفن')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن'), ('O', 'سایر'), ('N', 'ترجیح می\u200cدهم نگویم')], max_length=1, null=True, verbose_name='جنسیت')),
                ('relationship_status', models.CharField(blank=True, choices=[('single', 'مجرد'), ('married', 'متأهل'), ('divorced', 'مطلقه'), ('widowed', 'بیوه'), ('in_relationship', 'در رابطه'), ('complicated', 'پیچیده'), ('prefer_not_to_say', 'ترجیح می\u200cدهم نگویم')], max_length=20, null=True, verbose_name='وضعیت رابطه')),
                ('job_status', models.CharField(blank=True, choices=[('employed', 'شاغل'), ('unemployed', 'بیکار'), ('student', 'دانشجو'), ('retired', 'بازنشسته'), ('self_employed', 'خویش\u200cفرما'), ('freelancer', 'فریلنسر'), ('homemaker', 'خانه\u200cدار'), ('prefer_not_to_say', 'ترجیح می\u200cدهم نگویم')], max_length=20, null=True, verbose_name='وضعیت شغلی')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='شغل')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('country', models.CharField(blank=True, default='ایران', max_length=100, null=True, verbose_name='کشور')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='عکس پروفایل')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffee_readings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
