# Generated by Django 5.1.6 on 2025-12-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_file_options_alter_file_created_at_customuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar', 'العربية'), ('tr', 'Türkçe'), ('az', 'Azərbaycan'), ('ru', 'Русский')], default='fa', max_length=5, verbose_name='زبان'),
        ),
    ]
