# Generated by Django 5.1.6 on 2025-12-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar', 'العربية'), ('tr', 'Türkçe'), ('az', 'Azərbaycan'), ('ru', 'Русский')], default='en', max_length=5, verbose_name='زبان'),
        ),
    ]
