# Generated by Django 5.1.6 on 2025-12-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_update_default_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('fa', 'فارسی (Persian)'), ('ar', 'العربية (Arabic)'), ('tr', 'Türkçe (Turkish)'), ('az', 'Azərbaycan (Azerbaijani)'), ('ur', 'اردو (Urdu)'), ('he', 'עברית (Hebrew)'), ('en', 'English'), ('es', 'Español (Spanish)'), ('fr', 'Français (French)'), ('de', 'Deutsch (German)'), ('it', 'Italiano (Italian)'), ('pt', 'Português (Portuguese)'), ('ru', 'Русский (Russian)'), ('pl', 'Polski (Polish)'), ('nl', 'Nederlands (Dutch)'), ('cs', 'Čeština (Czech)'), ('el', 'Ελληνικά (Greek)'), ('sv', 'Svenska (Swedish)'), ('no', 'Norsk (Norwegian)'), ('da', 'Dansk (Danish)'), ('fi', 'Suomi (Finnish)'), ('ro', 'Română (Romanian)'), ('hu', 'Magyar (Hungarian)'), ('uk', 'Українська (Ukrainian)'), ('zh', '中文 (Chinese)'), ('ja', '日本語 (Japanese)'), ('ko', '한국어 (Korean)'), ('hi', 'हिन्दी (Hindi)'), ('bn', 'বাংলা (Bengali)'), ('th', 'ไทย (Thai)'), ('vi', 'Tiếng Việt (Vietnamese)'), ('id', 'Bahasa Indonesia (Indonesian)'), ('ms', 'Bahasa Melayu (Malay)'), ('ta', 'தமிழ் (Tamil)'), ('te', 'తెలుగు (Telugu)'), ('ml', 'മലയാളം (Malayalam)'), ('kn', 'ಕನ್ನಡ (Kannada)'), ('gu', 'ગુજરાતી (Gujarati)'), ('pa', 'ਪੰਜਾਬੀ (Punjabi)'), ('mr', 'मराठी (Marathi)'), ('ne', 'नेपाली (Nepali)'), ('si', 'සිංහල (Sinhala)'), ('my', 'မြန်မာ (Burmese)'), ('km', 'ខ្មែរ (Khmer)'), ('lo', 'ລາວ (Lao)'), ('sw', 'Kiswahili (Swahili)'), ('am', 'አማርኛ (Amharic)'), ('zu', 'isiZulu (Zulu)'), ('af', 'Afrikaans'), ('ha', 'Hausa'), ('yo', 'Yorùbá (Yoruba)'), ('ig', 'Igbo'), ('eo', 'Esperanto')], default='en', max_length=5, verbose_name='زبان'),
        ),
    ]
