# Generated by Django 5.1.6 on 2025-12-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_fortuneprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'فارسی (Persian)'), ('ar', 'العربية (Arabic)'), ('tr', 'Türkçe (Turkish)'), ('es', 'Español (Spanish)'), ('ur', 'اردو (Urdu)'), ('fr', 'Français (French)'), ('de', 'Deutsch (German)'), ('it', 'Italiano (Italian)'), ('pt', 'Português (Portuguese)'), ('ru', 'Русский (Russian)'), ('ja', '日本語 (Japanese)'), ('ko', '한국어 (Korean)'), ('he', 'עברית (Hebrew)'), ('hi', 'हिन्दी (Hindi)'), ('id', 'Bahasa Indonesia (Indonesian)'), ('th', 'ไทย (Thai)'), ('vi', 'Tiếng Việt (Vietnamese)'), ('bn', 'বাংলা (Bengali)'), ('ms', 'Bahasa Melayu (Malay)'), ('zh', '中文 (Chinese)'), ('pl', 'Polski (Polish)'), ('nl', 'Nederlands (Dutch)'), ('uk', 'Українська (Ukrainian)'), ('ro', 'Română (Romanian)'), ('el', 'Ελληνικά (Greek)'), ('cs', 'Čeština (Czech)'), ('sv', 'Svenska (Swedish)'), ('no', 'Norsk (Norwegian)'), ('da', 'Dansk (Danish)'), ('fi', 'Suomi (Finnish)'), ('hu', 'Magyar (Hungarian)'), ('az', 'Azərbaycan (Azerbaijani)'), ('ta', 'தமிழ் (Tamil)'), ('te', 'తెలుగు (Telugu)'), ('mr', 'मराठी (Marathi)'), ('gu', 'ગુજરાતી (Gujarati)'), ('pa', 'ਪੰਜਾਬੀ (Punjabi)'), ('ml', 'മലയാളം (Malayalam)'), ('kn', 'ಕನ್ನಡ (Kannada)'), ('ne', 'नेपाली (Nepali)'), ('my', 'မြန်မာ (Burmese)'), ('km', 'ខ្មែរ (Khmer)'), ('lo', 'ລາວ (Lao)'), ('si', 'සිංහල (Sinhala)'), ('sw', 'Kiswahili (Swahili)'), ('am', 'አማርኛ (Amharic)'), ('ha', 'Hausa'), ('yo', 'Yorùbá (Yoruba)'), ('ig', 'Igbo'), ('zu', 'isiZulu (Zulu)'), ('af', 'Afrikaans'), ('eo', 'Esperanto')], default='en', max_length=5, verbose_name='زبان'),
        ),
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کارت')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام انگلیسی')),
                ('suit', models.CharField(choices=[('major', 'Major Arcana'), ('wands', 'Wands'), ('cups', 'Cups'), ('swords', 'Swords'), ('pentacles', 'Pentacles')], max_length=20, verbose_name='نوع کارت')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='شماره کارت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tarot_cards/', verbose_name='عکس کارت')),
                ('meaning', models.TextField(blank=True, null=True, verbose_name='معنی کارت')),
                ('reversed_meaning', models.TextField(blank=True, null=True, verbose_name='معنی وارونه')),
                ('emoji', models.CharField(blank=True, max_length=10, null=True, verbose_name='ایموجی')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'کارت تاروت',
                'verbose_name_plural': 'کارت\u200cهای تاروت',
                'ordering': ['order', 'suit', 'number'],
                'unique_together': {('suit', 'number', 'name')},
            },
        ),
    ]
