# Generated by Django 5.1.6 on 2025-12-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_customuser_language_tarotcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotcard',
            name='names_translations',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object with language codes as keys and translated names as values. Example: {"en": "The Fool", "fa": "احمق", "ar": "الأحمق"}', verbose_name='ترجمه نام\u200cها'),
        ),
        migrations.AlterField(
            model_name='tarotcard',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام کارت (پیش\u200cفرض)'),
        ),
    ]
