# Generated by Django 5.1.6 on 2025-12-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tarotcard_names_translations_alter_tarotcard_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarotcard',
            name='image',
        ),
    ]
