# Generated by Django 5.1.6 on 2025-12-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_tarotcard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tarotcards', verbose_name='عکس کارت'),
        ),
    ]
